#docker-composeのバージョン
version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432' # ホストからゲストへポートフォワード
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db # DB側のコンテナが出来上がってからrailsを実行
    ports:
      - 3000:3000
    volumes:
      - .:/vocabulary # ソースコード変更したらDocker側も即反映されるように
    env_file: .env.dev
