apiVersion: v1
kind: Service
metadata:
  name: bocabulary-svc
spec:
  type: NodePort
  selector:
    app: bocabulary
  ports:
  - name: http
    port: 80
    targetPort: 3000 # アプリケーションにアクセスを受け渡す時のポート番号
