# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

QuestionSimilar.create(question_id: "1", similar_word: "acetic acid")
QuestionSimilar.create(question_id: "1", similar_word: "acetylene")
QuestionSimilar.create(question_id: "1", similar_word: "acrylamide")
QuestionSimilar.create(question_id: "2", similar_word: "bulk")
QuestionSimilar.create(question_id: "2", similar_word: "degree")
QuestionSimilar.create(question_id: "2", similar_word: "extent")
QuestionSimilar.create(question_id: "3", similar_word: "autotroph")
QuestionSimilar.create(question_id: "3", similar_word: "autotroph")
QuestionSimilar.create(question_id: "3", similar_word: "fauna")
QuestionSimilar.create(question_id: "4", similar_word: "bottom")
QuestionSimilar.create(question_id: "4", similar_word: "clue")
QuestionSimilar.create(question_id: "4", similar_word: "conquerable")
QuestionSimilar.create(question_id: "5", similar_word: "affirmation")
QuestionSimilar.create(question_id: "5", similar_word: "blessing")
QuestionSimilar.create(question_id: "5", similar_word: "approbation")
QuestionSimilar.create(question_id: "6", similar_word: "artistic")
QuestionSimilar.create(question_id: "6", similar_word: "canon")
QuestionSimilar.create(question_id: "6", similar_word: "artist")
QuestionSimilar.create(question_id: "7", similar_word: "aggressor")
QuestionSimilar.create(question_id: "7", similar_word: "beleaguer")
QuestionSimilar.create(question_id: "7", similar_word: "blitz")
QuestionSimilar.create(question_id: "8", similar_word: "attentiveness")
QuestionSimilar.create(question_id: "8", similar_word: "focused")
QuestionSimilar.create(question_id: "8", similar_word: "hang")
QuestionSimilar.create(question_id: "9", similar_word: "anticlockwise")
QuestionSimilar.create(question_id: "9", similar_word: "backward")
QuestionSimilar.create(question_id: "9", similar_word: "counterclockwise")
QuestionSimilar.create(question_id: "10", similar_word: "bases")
QuestionSimilar.create(question_id: "10", similar_word: "bottom")
QuestionSimilar.create(question_id: "10", similar_word: "escutcheon")
QuestionSimilar.create(question_id: "11", similar_word: "behalf")
QuestionSimilar.create(question_id: "11", similar_word: "behave")
QuestionSimilar.create(question_id: "11", similar_word: "behavioral")
QuestionSimilar.create(question_id: "12", similar_word: "accept")
QuestionSimilar.create(question_id: "12", similar_word: "article of faith")
QuestionSimilar.create(question_id: "12", similar_word: "ascription")
QuestionSimilar.create(question_id: "13", similar_word: "antenatal")
QuestionSimilar.create(question_id: "13", similar_word: "Apgar score")
QuestionSimilar.create(question_id: "13", similar_word: "birth defect")
QuestionSimilar.create(question_id: "14", similar_word: "Abo")
QuestionSimilar.create(question_id: "14", similar_word: "atrial")
QuestionSimilar.create(question_id: "14", similar_word: "auricular")
QuestionSimilar.create(question_id: "15", similar_word: "blast")
QuestionSimilar.create(question_id: "15", similar_word: "blown")
QuestionSimilar.create(question_id: "15", similar_word: "breeze")
QuestionSimilar.create(question_id: "16", similar_word: "animal")
QuestionSimilar.create(question_id: "16", similar_word: "axial")
QuestionSimilar.create(question_id: "16", similar_word: "biodynamics")
QuestionSimilar.create(question_id: "17", similar_word: "bagel")
QuestionSimilar.create(question_id: "17", similar_word: "baguette")
QuestionSimilar.create(question_id: "17", similar_word: "bannock")
QuestionSimilar.create(question_id: "18", similar_word: "aerobic")
QuestionSimilar.create(question_id: "18", similar_word: "anaerobic respiration")
QuestionSimilar.create(question_id: "18", similar_word: "asphyxiate")
QuestionSimilar.create(question_id: "19", similar_word: "aunt")
QuestionSimilar.create(question_id: "19", similar_word: "auntie")
QuestionSimilar.create(question_id: "19", similar_word: "baby daddy")
QuestionSimilar.create(question_id: "20", similar_word: "castellated")
QuestionSimilar.create(question_id: "20", similar_word: "convention centre")
QuestionSimilar.create(question_id: "20", similar_word: "campanile")

